# when the service's volumes are set to ./*:/usr/src/*/, docker will reflect the changes in local environment

services:
  redis:
    image: redis:7.4.0-alpine
    container_name: redis

  django:
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/usr/src/django/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - database
      - redis

  database:
    image: postgres:16.3-alpine
    container_name: database
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    command: -p 5432

volumes:
  postgres: